export const BASE_ELEMENTS = ["fire", "water", "earth", "wind"];

export const ELEMENTS = {
  // Tier 1: Base elements
  fire:   { id: "fire",   name: "Fire",   spellType: "damage", attack: 8,  tier: 1, animationTags: { idle: "ember glow", onCast: "fire lash" } },
  water:  { id: "water",  name: "Water",  spellType: "damage", attack: 6,  tier: 1, animationTags: { idle: "water shimmer", onCast: "water splash" } },
  earth:  { id: "earth",  name: "Earth",  spellType: "damage", attack: 7,  tier: 1, animationTags: { idle: "stone hum", onCast: "earth jab" } },
  wind:   { id: "wind",   name: "Wind",   spellType: "damage", attack: 6,  tier: 1, animationTags: { idle: "air swirl", onCast: "wind slash" } },

  // Tier 1: Simple combos (base + base)
  steam:    { id: "steam",    name: "Steam",    spellType: "damage", attack: 9,  tier: 1, animationTags: { onForm: "steam burst", onCast: "steam jet" } },
  plant:    { id: "plant",    name: "Plant",    spellType: "damage", attack: 8,  tier: 1, animationTags: { onForm: "leaf grow", onCast: "vine strike" } },
  wave:     { id: "wave",     name: "Wave",     spellType: "damage", attack: 10, tier: 1, animationTags: { onForm: "splash crest", onCast: "wave crash" } },
  lava:     { id: "lava",     name: "Lava",     spellType: "damage", attack: 14, tier: 1, animationTags: { onForm: "lava bubble", onCast: "lava burst" } },
  smoke:    { id: "smoke",    name: "Smoke",    spellType: "debuff", effectId: "blind", tier: 1, animationTags: { onForm: "smoke puff", onCast: "smoke veil" } },
  dust:     { id: "dust",     name: "Dust",     spellType: "debuff", effectId: "slow",  tier: 1, animationTags: { onForm: "dust swirl", onCast: "dust choke" } },
  volcano:  { id: "volcano",  name: "Volcano",  spellType: "damage", attack: 17, tier: 1, animationTags: { onCast: "volcano eruption" } },
  lake:     { id: "lake",     name: "Lake",     spellType: "heal",   heal: 14,   tier: 1, effectId: "regeneration", animationTags: { onForm: "water pool", onCast: "lake blessing" } },
  mountain: { id: "mountain", name: "Mountain", spellType: "buff",   effectId: "shield", tier: 1, animationTags: { onForm: "stone rise", onCast: "granite ward" } },
  storm:    { id: "storm",    name: "Storm",    spellType: "damage", attack: 16, tier: 1, animationTags: { onCast: "storm strike" } },

  // Tier 2: Intermediate combos (require combining Tier 1 results)
  fog:       { id: "fog",       name: "Fog",       spellType: "debuff", effectId: "weaken", tier: 2, animationTags: { onCast: "fog wrap" } },
  mud:       { id: "mud",       name: "Mud",       spellType: "debuff", effectId: "slow",   tier: 2, animationTags: { onCast: "mud snare" } },
  rain:      { id: "rain",      name: "Rain",      spellType: "heal",   heal: 18, effectId: "regeneration", tier: 2, animationTags: { onCast: "rain restore" } },
  snow:      { id: "snow",      name: "Snow",      spellType: "debuff", effectId: "slow",   tier: 2, animationTags: { onCast: "snow drift" } },
  ice:       { id: "ice",       name: "Ice",       spellType: "debuff", effectId: "slow",   tier: 2, animationTags: { onCast: "ice bind" } },
  sand:      { id: "sand",      name: "Sand",      spellType: "damage", attack: 11, tier: 2, animationTags: { onCast: "sand lash" } },
  ash:       { id: "ash",       name: "Ash",       spellType: "debuff", effectId: "weaken", tier: 2, animationTags: { onCast: "ash cloud" } },
  stone:     { id: "stone",     name: "Stone",     spellType: "buff",   effectId: "shield", tier: 2, animationTags: { onCast: "stone guard" } },
  cloud:     { id: "cloud",     name: "Cloud",     spellType: "buff",   effectId: "ward",   tier: 2, animationTags: { onCast: "cloud veil" } },
  mist:      { id: "mist",      name: "Mist",      spellType: "debuff", effectId: "blind",  tier: 2, animationTags: { onCast: "mist veil" } },
  ocean:     { id: "ocean",     name: "Ocean",     spellType: "damage", attack: 19, tier: 2, animationTags: { onCast: "ocean surge" } },
  swamp:     { id: "swamp",     name: "Swamp",     spellType: "debuff", effectId: "slow",   tier: 2, animationTags: { onCast: "swamp drag" } },
  tree:      { id: "tree",      name: "Tree",      spellType: "buff",   effectId: "regeneration", tier: 2, animationTags: { onCast: "tree ward" } },
  forest:    { id: "forest",    name: "Forest",    spellType: "buff",   effectId: "powerUp", tier: 2, animationTags: { onCast: "forest focus" } },
  tea:       { id: "tea",       name: "Tea",       spellType: "heal",   heal: 12, effectId: "cleanse", tier: 2, animationTags: { onCast: "tea soothe" } },
  lily:      { id: "lily",      name: "Lily",      spellType: "heal",   heal: 16, tier: 2, animationTags: { onCast: "lily bloom" } },
  pollen:    { id: "pollen",    name: "Pollen",    spellType: "debuff", effectId: "blind", tier: 2, animationTags: { onCast: "pollen burst" } },
  incense:   { id: "incense",   name: "Incense",   spellType: "buff",   effectId: "ward",  tier: 2, animationTags: { onCast: "incense aura" } },
  clay:      { id: "clay",      name: "Clay",      spellType: "buff",   effectId: "shield", tier: 2, animationTags: { onCast: "clay coat" } },
  glass:     { id: "glass",     name: "Glass",     spellType: "damage", attack: 13, effectId: "defenseDown", tier: 2, animationTags: { onCast: "glass shard" } },
  ward:      { id: "ward",      name: "Ward",      spellType: "buff",   effectId: "ward",   tier: 2, animationTags: { onCast: "ward ring" } },
  regeneration: { id: "regeneration", name: "Regeneration", spellType: "heal", heal: 10, effectId: "regeneration", tier: 2, animationTags: { onCast: "green pulse" } },
  smog:      { id: "smog",      name: "Smog",      spellType: "debuff", effectId: "poison", tier: 2, animationTags: { onCast: "smog burst" } },
  thunder:   { id: "thunder",   name: "Thunder",   spellType: "damage", attack: 15, tier: 2, animationTags: { onCast: "thunder crack" } },
  lightning: { id: "lightning", name: "Lightning", spellType: "damage", attack: 18, tier: 2, animationTags: { onCast: "lightning strike" } },
  sandstorm: { id: "sandstorm", name: "Sandstorm", spellType: "damage", attack: 17, effectId: "blind", tier: 2, animationTags: { onCast: "sandstorm howl" } },
  hurricane: { id: "hurricane", name: "Hurricane", spellType: "damage", attack: 18, effectId: "slow", tier: 2, animationTags: { onCast: "hurricane spin" } },
  tornado:   { id: "tornado",   name: "Tornado",   spellType: "damage", attack: 17, effectId: "slow", tier: 2, animationTags: { onCast: "tornado spin" } },
  thunderstorm: { id: "thunderstorm", name: "Thunderstorm", spellType: "damage", attack: 21, effectId: "weaken", tier: 2, animationTags: { onCast: "thunderstorm blast" } },
  blizzard:  { id: "blizzard",  name: "Blizzard",  spellType: "damage", attack: 20, effectId: "slow", tier: 2, animationTags: { onCast: "blizzard surge" } },
  tsunami:   { id: "tsunami",   name: "Tsunami",   spellType: "damage", attack: 24, tier: 2, animationTags: { onCast: "tsunami crash" } },
  shadow:    { id: "shadow",    name: "Shadow",    spellType: "debuff", effectId: "silence", tier: 2, animationTags: { onCast: "shadow bind" } },
  glacier:   { id: "glacier",   name: "Glacier",   spellType: "debuff", effectId: "slow", tier: 2, animationTags: { onCast: "glacier lock" } },
  meteor:    { id: "meteor",    name: "Meteor",    spellType: "damage", attack: 22, tier: 2, animationTags: { onCast: "meteor impact" } },
  // Tier 2: More combos (full-circle / multiplayer variety)
  ember:     { id: "ember",     name: "Ember",     spellType: "damage", attack: 9,  tier: 2, animationTags: { onCast: "ember glow" } },
  frost:     { id: "frost",     name: "Frost",     spellType: "debuff", effectId: "slow", tier: 2, animationTags: { onCast: "frost bite" } },
  river:     { id: "river",     name: "River",     spellType: "damage", attack: 11, tier: 2, animationTags: { onCast: "river rush" } },
  geyser:    { id: "geyser",    name: "Geyser",    spellType: "damage", attack: 15, tier: 2, animationTags: { onCast: "geyser burst" } },
  hail:      { id: "hail",      name: "Hail",      spellType: "damage", attack: 14, effectId: "weaken", tier: 2, animationTags: { onCast: "hail strike" } },
  spark:     { id: "spark",     name: "Spark",     spellType: "damage", attack: 10, tier: 2, animationTags: { onCast: "spark flash" } },
  dew:       { id: "dew",       name: "Dew",       spellType: "heal",   heal: 12, tier: 2, animationTags: { onCast: "dew restore" } },
  bloom:     { id: "bloom",     name: "Bloom",     spellType: "heal",   heal: 16, effectId: "regeneration", tier: 2, animationTags: { onCast: "bloom heal" } },
  sleet:     { id: "sleet",     name: "Sleet",     spellType: "debuff", effectId: "slow", tier: 2, animationTags: { onCast: "sleet chill" } },
  flare:     { id: "flare",    name: "Flare",     spellType: "damage", attack: 19, tier: 2, animationTags: { onCast: "flare burst" } },
  obsidian:  { id: "obsidian",  name: "Obsidian",  spellType: "damage", attack: 15, effectId: "defenseDown", tier: 2, animationTags: { onCast: "obsidian shard" } },
  crystal:   { id: "crystal",   name: "Crystal",   spellType: "buff",   effectId: "ward", tier: 2, animationTags: { onCast: "crystal ward" } },
  brine:     { id: "brine",     name: "Brine",     spellType: "debuff", effectId: "weaken", tier: 2, animationTags: { onCast: "brine sting" } },
  monsoon:   { id: "monsoon",   name: "Monsoon",   spellType: "damage", attack: 20, effectId: "slow", tier: 2, animationTags: { onCast: "monsoon deluge" } },
  comet:     { id: "comet",     name: "Comet",     spellType: "damage", attack: 21, tier: 2, animationTags: { onCast: "comet trail" } },
  void:      { id: "void",     name: "Void",      spellType: "debuff", effectId: "silence", tier: 2, animationTags: { onCast: "void pull" } },
  life:      { id: "life",      name: "Life",      spellType: "heal",   heal: 18, effectId: "regeneration", tier: 2, animationTags: { onCast: "life pulse" } },
  death:     { id: "death",     name: "Death",     spellType: "damage", attack: 18, effectId: "weaken", tier: 2, animationTags: { onCast: "death touch" } },
  light:     { id: "light",     name: "Light",     spellType: "buff",   effectId: "powerUp", tier: 2, animationTags: { onCast: "light surge" } },
  darkness:  { id: "darkness",  name: "Darkness",  spellType: "debuff", effectId: "blind", tier: 2, animationTags: { onCast: "darkness veil" } },
  // Infinite Craft–style (IC solver dataset–inspired)
  sun:       { id: "sun",       name: "Sun",       spellType: "damage", attack: 12, tier: 2, animationTags: { onCast: "sun beam" } },
  moon:      { id: "moon",      name: "Moon",      spellType: "buff",   effectId: "ward", tier: 2, animationTags: { onCast: "moon veil" } },
  rainbow:   { id: "rainbow",   name: "Rainbow",   spellType: "buff",   effectId: "powerUp", tier: 2, animationTags: { onCast: "rainbow surge" } },
  energy:    { id: "energy",    name: "Energy",    spellType: "buff",   effectId: "powerUp", tier: 2, animationTags: { onCast: "energy pulse" } },
  love:      { id: "love",      name: "Love",      spellType: "heal",   heal: 16, effectId: "regeneration", tier: 2, animationTags: { onCast: "love heal" } },
  tide:      { id: "tide",      name: "Tide",      spellType: "damage", attack: 11, tier: 2, animationTags: { onCast: "tide pull" } },

  // Tier 3: Advanced combos (combine Tier 2 results)
  magma:     { id: "magma",     name: "Magma",     spellType: "damage", attack: 16, effectId: "defenseDown", tier: 3, animationTags: { onCast: "magma flow" } },
  tempest:   { id: "tempest",   name: "Tempest",   spellType: "damage", attack: 20, effectId: "slow", tier: 3, animationTags: { onCast: "tempest howl" } },
  torrent:   { id: "torrent",   name: "Torrent",   spellType: "damage", attack: 22, tier: 3, animationTags: { onCast: "torrent rush" } },
  grove:     { id: "grove",     name: "Grove",     spellType: "heal",   heal: 20, effectId: "regeneration", tier: 3, animationTags: { onCast: "grove bloom" } },
  mirage:    { id: "mirage",    name: "Mirage",    spellType: "debuff", effectId: "blind", tier: 3, animationTags: { onCast: "mirage shimmer" } },
  blood:     { id: "blood",     name: "Blood",     spellType: "damage", attack: 20, effectId: "poison", tier: 3, animationTags: { onCast: "blood curse" } },
  spirit:    { id: "spirit",    name: "Spirit",    spellType: "buff",   effectId: "ward", tier: 3, animationTags: { onCast: "spirit ward" } },
  prism:     { id: "prism",     name: "Prism",     spellType: "buff",   effectId: "powerUp", tier: 3, animationTags: { onCast: "prism focus" } },
  nebula:    { id: "nebula",    name: "Nebula",    spellType: "debuff", effectId: "blind", tier: 3, animationTags: { onCast: "nebula cloud" } },
  phoenix:   { id: "phoenix",   name: "Phoenix",   spellType: "damage", attack: 23, effectId: "weaken", tier: 3, animationTags: { onCast: "phoenix flame" } },
  dragon:    { id: "dragon",    name: "Dragon",    spellType: "damage", attack: 24, tier: 3, animationTags: { onCast: "dragon breath" } },
  twilight:  { id: "twilight",  name: "Twilight",  spellType: "debuff", effectId: "slow", tier: 3, animationTags: { onCast: "twilight bind" } },
  chaos:     { id: "chaos",     name: "Chaos",     spellType: "damage", attack: 21, effectId: "weaken", tier: 3, animationTags: { onCast: "chaos surge" } },
  angel:     { id: "angel",     name: "Angel",     spellType: "heal",   heal: 22, effectId: "cleanse", tier: 3, animationTags: { onCast: "angel grace" } },
  demon:     { id: "demon",     name: "Demon",     spellType: "damage", attack: 22, effectId: "poison", tier: 3, animationTags: { onCast: "demon strike" } },

  // Tier 4: Powerful combos (combine Tier 3 results)
  inferno:      { id: "inferno",      name: "Inferno",      spellType: "damage", attack: 24, effectId: "weaken",  tier: 4, animationTags: { onCast: "inferno blaze" } },
  maelstrom:    { id: "maelstrom",    name: "Maelstrom",    spellType: "damage", attack: 26, tier: 4, animationTags: { onCast: "maelstrom vortex" } },
  sanctuary:    { id: "sanctuary",    name: "Sanctuary",    spellType: "heal",   heal: 24, effectId: "shield", tier: 4, animationTags: { onCast: "sanctuary light" } },
  voidmist:     { id: "voidmist",     name: "Voidmist",     spellType: "debuff", effectId: "silence", tier: 4, animationTags: { onCast: "voidmist eclipse" } },
  crystalstorm: { id: "crystalstorm", name: "Crystalstorm", spellType: "damage", attack: 22, effectId: "slow", tier: 4, animationTags: { onCast: "crystalstorm shatter" } },

  // Tier 5: Endgame combos (combine Tier 4 results)
  apocalypse: { id: "apocalypse", name: "Apocalypse", spellType: "damage", attack: 30, tier: 5, animationTags: { onCast: "apocalypse rain" } },
  genesis:    { id: "genesis",    name: "Genesis",    spellType: "heal",   heal: 28, effectId: "regeneration", tier: 5, animationTags: { onCast: "genesis wave" } },
  eclipse:    { id: "eclipse",    name: "Eclipse",    spellType: "damage", attack: 28, effectId: "silence", tier: 5, animationTags: { onCast: "eclipse darkness" } },

  // Fallback (kept for enemy AI, never craftable by player)
  fusion: { id: "fusion", name: "Fusion", spellType: "damage", attack: 10, tier: 99, animationTags: { onForm: "arc pulse", onCast: "arc pulse" } },
};

export const STATUS_EMOJI = {
  shield: '🛡️',
  regeneration: '💚',
  cleanse: '🧽',
  slow: '🐌',
  blind: '👁️',
  poison: '☠️',
  silence: '🔇',
  powerUp: '🧨',
  weaken: '🪓',
  defenseDown: '🧱',
  weakSpot: '🎯',
  ward: '🛡️',
};

export const SPELL_TYPE_COLORS = {
  damage: '#ff4444',
  heal: '#44ff88',
  buff: '#4488ff',
  debuff: '#aa44ff',
};
