import { ELEMENTS } from "./elements.js";

export function recipeKey(a, b) {
  return [a, b].sort().join("|");
}

const R = (a, b, resultId) => [recipeKey(a, b), resultId];

export const RECIPE_MAP = new Map([
  R("fire", "fire", "volcano"),
  R("water", "water", "lake"),
  R("earth", "earth", "mountain"),
  R("wind", "wind", "storm"),
  R("fire", "water", "steam"),
  R("water", "earth", "plant"),
  R("water", "wind", "wave"),
  R("fire", "earth", "lava"),
  R("fire", "wind", "smoke"),
  R("earth", "wind", "dust"),
  R("steam", "water", "rain"),
  R("steam", "smoke", "fog"),
  R("steam", "earth", "mud"),
  R("storm", "fire", "lightning"),
  R("storm", "water", "tsunami"),
  R("storm", "wind", "blizzard"),
  R("blizzard", "earth", "glacier"),
  R("lava", "storm", "meteor"),
  R("shadow", "storm", "meteor"),
  R("shadow", "water", "tsunami"),
  R("shadow", "fire", "meteor"),
  R("shadow", "earth", "glacier"),
  R("steam", "fire", "cloud"),
  R("steam", "wind", "mist"),
  R("steam", "lava", "stone"),
  R("steam", "dust", "sand"),
  R("steam", "lake", "ocean"),
  R("steam", "storm", "blizzard"),
  R("lava", "water", "stone"),
  R("lava", "earth", "volcano"),
  R("lava", "wind", "ash"),
  R("lava", "smoke", "ash"),
  R("lava", "dust", "glass"),
  R("lava", "lake", "ocean"),
  R("smoke", "water", "fog"),
  R("smoke", "earth", "ash"),
  R("smoke", "wind", "storm"),
  R("smoke", "dust", "smog"),
  R("smoke", "lake", "mist"),
  R("smoke", "mountain", "cloud"),
  R("smoke", "storm", "thunder"),
  R("dust", "water", "mud"),
  R("dust", "fire", "ash"),
  R("dust", "earth", "sand"),
  R("dust", "wind", "sandstorm"),
  R("dust", "lake", "clay"),
  R("dust", "storm", "tornado"),
  R("plant", "fire", "ash"),
  R("plant", "water", "lily"),
  R("plant", "earth", "tree"),
  R("plant", "wind", "pollen"),
  R("plant", "steam", "tea"),
  R("plant", "lava", "ash"),
  R("plant", "smoke", "incense"),
  R("plant", "dust", "pollen"),
  R("plant", "lake", "lily"),
  R("plant", "mountain", "forest"),
  R("plant", "storm", "lightning"),
  R("wave", "fire", "steam"),
  R("wave", "earth", "sand"),
  R("wave", "wind", "hurricane"),
  R("wave", "lake", "ocean"),
  R("wave", "storm", "tsunami"),
  R("cloud", "fire", "lightning"),
  R("cloud", "water", "rain"),
  R("cloud", "earth", "fog"),
  R("cloud", "wind", "storm"),
  R("cloud", "steam", "mist"),
  R("cloud", "lava", "ash"),
  R("cloud", "smoke", "smog"),
  R("cloud", "dust", "sandstorm"),
  R("cloud", "lake", "mist"),
  R("cloud", "mountain", "snow"),
  R("cloud", "storm", "thunderstorm"),
  R("storm", "earth", "thunder"),
  R("storm", "smoke", "thunder"),
  R("storm", "dust", "sandstorm"),
  R("storm", "lake", "tsunami"),
  R("storm", "mountain", "blizzard"),
  R("snow", "water", "ice"),
  R("snow", "wind", "blizzard"),
  R("snow", "earth", "glacier"),
  R("snow", "fire", "water"),
  R("ice", "wind", "blizzard"),
  R("ice", "earth", "glacier"),
  R("ice", "fire", "water"),
  R("ice", "storm", "blizzard"),
  R("mud", "fire", "clay"),
  R("mud", "plant", "swamp"),
  R("mud", "water", "swamp"),
  R("sand", "fire", "glass"),
  R("sand", "water", "clay"),
  R("sand", "wind", "sandstorm"),
  R("sand", "storm", "sandstorm"),
  R("ash", "water", "mud"),
  R("ash", "wind", "smog"),
  R("ash", "earth", "clay"),
  R("stone", "fire", "lava"),
  R("stone", "water", "sand"),
  R("stone", "wind", "sand"),
  R("stone", "plant", "forest"),
  R("ocean", "fire", "steam"),
  R("ocean", "wind", "hurricane"),
  R("ocean", "storm", "tsunami"),
  R("forest", "fire", "ash"),
  R("forest", "water", "swamp"),
  R("forest", "wind", "hurricane"),
  R("tea", "storm", "thunder"),
  R("incense", "shadow", "ward"),
  R("lily", "rain", "regeneration"),
  R("pollen", "wind", "sandstorm"),
  R("pollen", "smoke", "smog"),

  // Tier 3: Advanced combos
  R("lava", "stone", "magma"),
  R("storm", "hurricane", "tempest"),
  R("ocean", "tsunami", "torrent"),
  R("forest", "tree", "grove"),
  R("sand", "mist", "mirage"),

  // Tier 4: Powerful combos
  R("magma", "volcano", "inferno"),
  R("tempest", "torrent", "maelstrom"),
  R("grove", "rain", "sanctuary"),
  R("mirage", "shadow", "voidmist"),
  R("glacier", "blizzard", "crystalstorm"),

  // Tier 5: Endgame combos
  R("inferno", "maelstrom", "apocalypse"),
  R("sanctuary", "grove", "genesis"),
  R("voidmist", "meteor", "eclipse"),

  // ---- New elements: creation paths (full-circle / multiplayer) ----
  R("fire", "ash", "ember"),
  R("ice", "cloud", "frost"),
  R("ice", "wind", "frost"),
  R("water", "mountain", "river"),
  R("wave", "mountain", "river"),
  R("steam", "mountain", "geyser"),
  R("ice", "storm", "hail"),
  R("snow", "storm", "hail"),
  R("fire", "thunder", "spark"),
  R("mist", "plant", "dew"),
  R("fog", "plant", "dew"),
  R("plant", "rain", "bloom"),
  R("rain", "ice", "sleet"),
  R("rain", "snow", "sleet"),
  R("fire", "lightning", "flare"),
  R("lava", "ice", "obsidian"),
  R("stone", "lightning", "crystal"),
  R("ocean", "sand", "brine"),
  R("rain", "storm", "monsoon"),
  R("meteor", "ice", "comet"),
  R("meteor", "wind", "comet"),
  R("shadow", "shadow", "void"),
  R("tree", "rain", "life"),
  R("plant", "lake", "life"),
  R("grove", "water", "life"),
  R("shadow", "ash", "death"),
  R("lightning", "cloud", "light"),
  R("fire", "ward", "light"),
  R("shadow", "fog", "darkness"),
  R("shadow", "mist", "darkness"),
  R("life", "death", "blood"),
  R("life", "wind", "spirit"),
  R("life", "mist", "spirit"),
  R("light", "glass", "prism"),
  R("cloud", "void", "nebula"),
  R("mist", "void", "nebula"),
  R("fire", "life", "phoenix"),
  R("fire", "meteor", "dragon"),
  R("lava", "hurricane", "dragon"),
  R("light", "shadow", "twilight"),
  R("light", "darkness", "twilight"),
  R("void", "storm", "chaos"),
  R("void", "wind", "chaos"),
  R("light", "life", "angel"),
  R("fire", "death", "demon"),
  R("death", "lava", "demon"),

  // ---- Fill gaps: reuse existing elements so more combos work ----
  R("fire", "ice", "water"),
  R("fire", "glacier", "steam"),
  R("rain", "fire", "steam"),
  R("rain", "earth", "mud"),
  R("steam", "steam", "cloud"),
  R("wave", "wave", "tsunami"),
  R("snow", "snow", "blizzard"),
  R("ice", "ice", "glacier"),
  R("dust", "dust", "sand"),
  R("smoke", "smoke", "fog"),
  R("clay", "fire", "stone"),
  R("mountain", "wind", "snow"),
  R("cloud", "ice", "hail"),
  R("lake", "earth", "river"),
  R("plant", "dew", "bloom"),
  R("mist", "fire", "steam"),
  R("fog", "fire", "steam"),
  R("life", "water", "regeneration"),
  R("light", "earth", "crystal"),
  R("stone", "storm", "sand"),
  R("fire", "snow", "water"),
  R("fire", "frost", "water"),
  R("wind", "rain", "storm"),
  R("wind", "hail", "blizzard"),
  R("earth", "rain", "mud"),
  R("ocean", "earth", "clay"),
  R("shadow", "ice", "frost"),
  R("shadow", "rain", "darkness"),
  R("thunder", "water", "storm"),
  R("thunder", "earth", "lightning"),
  R("sand", "ice", "frost"),
  R("swamp", "fire", "steam"),
  R("forest", "rain", "grove"),
  R("tree", "storm", "lightning"),
  R("incense", "fire", "smoke"),
  R("ward", "shadow", "twilight"),
  R("regeneration", "life", "bloom"),
  R("smog", "water", "mud"),
  R("pollen", "water", "mud"),
  R("geyser", "earth", "stone"),
  R("river", "river", "lake"),
  R("river", "lake", "ocean"),
  R("river", "wind", "storm"),
  R("ember", "wind", "spark"),
  R("ember", "water", "ash"),
  R("frost", "fire", "water"),
  R("frost", "earth", "ice"),
  R("spark", "water", "steam"),
  R("spark", "earth", "lava"),
  R("dew", "fire", "steam"),
  R("dew", "wind", "mist"),
  R("bloom", "fire", "ash"),
  R("bloom", "wind", "pollen"),
  R("sleet", "earth", "mud"),
  R("sleet", "wind", "blizzard"),
  R("flare", "water", "steam"),
  R("flare", "earth", "lava"),
  R("obsidian", "fire", "lava"),
  R("obsidian", "water", "stone"),
  R("crystal", "fire", "lava"),
  R("crystal", "water", "ice"),
  R("brine", "fire", "steam"),
  R("brine", "earth", "clay"),
  R("monsoon", "earth", "swamp"),
  R("monsoon", "fire", "steam"),
  R("comet", "earth", "meteor"),
  R("comet", "fire", "meteor"),
  R("void", "fire", "shadow"),
  R("void", "water", "shadow"),
  R("void", "earth", "shadow"),
  R("void", "wind", "chaos"),
  R("life", "fire", "phoenix"),
  R("life", "earth", "tree"),
  R("life", "plant", "bloom"),
  R("death", "water", "blood"),
  R("death", "earth", "ash"),
  R("death", "wind", "void"),
  R("light", "water", "prism"),
  R("light", "fire", "flare"),
  R("light", "darkness", "twilight"),
  R("darkness", "fire", "shadow"),
  R("darkness", "water", "void"),
  R("darkness", "light", "twilight"),
  R("blood", "fire", "demon"),
  R("blood", "water", "life"),
  R("spirit", "fire", "phoenix"),
  R("spirit", "water", "life"),
  R("spirit", "death", "void"),
  R("prism", "water", "light"),
  R("prism", "darkness", "twilight"),
  R("nebula", "fire", "storm"),
  R("nebula", "water", "mist"),
  R("nebula", "light", "prism"),
  R("phoenix", "water", "steam"),
  R("phoenix", "death", "demon"),
  R("dragon", "water", "storm"),
  R("dragon", "earth", "volcano"),
  R("dragon", "ice", "blizzard"),
  R("twilight", "fire", "shadow"),
  R("twilight", "water", "mist"),
  R("chaos", "earth", "meteor"),
  R("chaos", "water", "maelstrom"),
  R("chaos", "light", "prism"),
  R("angel", "death", "spirit"),
  R("angel", "water", "sanctuary"),
  R("demon", "water", "blood"),
  R("demon", "light", "chaos"),

  // Infinite Craft–style (from IC solver format: first, second sorted; result with stats)
  R("fire", "light", "sun"),
  R("water", "light", "rainbow"),
  R("sun", "water", "rainbow"),
  R("moon", "water", "tide"),
  R("earth", "sun", "energy"),
  R("fire", "sun", "flare"),
  R("life", "life", "love"),
  R("light", "life", "angel"),
  R("water", "love", "life"),
  R("rain", "sun", "rainbow"),
  R("cloud", "sun", "light"),
  R("moon", "moon", "eclipse"),
  R("sun", "moon", "eclipse"),
  R("sun", "earth", "energy"),
  R("wind", "sun", "energy"),
  R("love", "fire", "phoenix"),
  R("love", "water", "rain"),
  R("energy", "fire", "lightning"),
  R("energy", "water", "storm"),
  R("rainbow", "water", "rain"),
  R("rainbow", "darkness", "twilight"),
  R("tide", "tide", "tsunami"),
]);

const FIZZLE_MESSAGES = [
  "The elements repel each other...",
  "The spell fizzles away...",
  "Nothing happens. Try a different combination.",
  "The magic dissipates harmlessly.",
  "These elements cannot be combined.",
  "The arcane energy scatters into nothing.",
  "The elements clash and cancel out.",
];

export function getRandomFizzleMessage() {
  return FIZZLE_MESSAGES[Math.floor(Math.random() * FIZZLE_MESSAGES.length)];
}

export function combineElements(a, b) {
  const key = recipeKey(a, b);
  const explicit = RECIPE_MAP.get(key);
  if (explicit && ELEMENTS[explicit]) return explicit;
  return null;
}

export function getAllRecipeRows() {
  const rows = [];
  for (const [key, resultId] of RECIPE_MAP.entries()) {
    const [a, b] = key.split("|");
    const result = ELEMENTS[resultId];
    if (!result) continue;
    rows.push({
      a,
      b,
      resultId,
      resultName: result.name,
      spellType: result.spellType,
      tier: result.tier ?? 1,
      detail: result.attack ?? result.heal ?? result.effectId ?? "-",
    });
  }
  rows.sort((x, y) => x.resultName.localeCompare(y.resultName));
  return rows;
}
